services:
  api01: &api
    build:
      context: .
    hostname: api01
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"  # Apenas o NGINX está exposto para o host.
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024
