services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    # environment:
    #   - PORT=9998
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    # environment:
    #   - PORT=9997

  # ld-tcp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ld-tcp
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "100MB"

  # ld:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ld
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "100MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"  # Apenas o NGINX está exposto para o host.
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024
