[package]
name = "load_balance"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
axum = "0.7.9"
hyper-util = { version = "0.1.10", features = ["client-legacy", "http2", "http1"] }
